FROM debian:bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates curl iproute2 iputils-ping procps \
  && rm -rf /var/lib/apt/lists/*

COPY entrypoint-web.sh /entrypoint-web.sh
RUN chmod +x /entrypoint-web.sh

ENTRYPOINT ["/entrypoint-web.sh"]

